micronaut:
  application:
    name: taskService
tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
    sampler:
      probability: 0.1
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
